<?php

/**
 * Provide a admin area view for the plugin
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 *
 * @link       https://medium.com/@michael.rhema
 * @since      1.0.0
 *
 * @package    Live_Screenshots
 * @subpackage Live_Screenshots/admin/partials
 */
?>

<!-- This file should primarily consist of HTML with a little bit of PHP. -->
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class LiveScreenshots {
	private $live_screenshots_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'live_screenshots_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'live_screenshots_page_init' ) );
	}

	public function live_screenshots_add_plugin_page() {
		add_options_page(
			'Live Screenshots', // page_title
			'Live Screenshots', // menu_title
			'manage_options', // capability
			'live-screenshots', // menu_slug
			array( $this, 'live_screenshots_create_admin_page' ) // function
		);
	}

	public function live_screenshots_create_admin_page() {
		$this->live_screenshots_options = get_option( 'live_screenshots_option_name' ); ?>

		<div class="wrap">
			<h2>Live Screenshots</h2>
			<p>Create a live screenshot of any webpage and refresh the image periodically.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'live_screenshots_option_group' );
					do_settings_sections( 'live-screenshots-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function live_screenshots_page_init() {
		register_setting(
			'live_screenshots_option_group', // option_group
			'live_screenshots_option_name', // option_name
			array( $this, 'live_screenshots_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'live_screenshots_setting_section', // id
			'Settings', // title
			array( $this, 'live_screenshots_section_info' ), // callback
			'live-screenshots-admin' // page
		);

		add_settings_field(
			'web_page_url_0', // id
			'Web-page URL', // title
			array( $this, 'web_page_url_0_callback' ), // callback
			'live-screenshots-admin', // page
			'live_screenshots_setting_section' // section
		);

		add_settings_field(
			'css_path_selector_to_capture_1', // id
			'CSS Path / Selector to capture', // title
			array( $this, 'css_path_selector_to_capture_1_callback' ), // callback
			'live-screenshots-admin', // page
			'live_screenshots_setting_section' // section
		);

		add_settings_field(
			'image_or_html_2', // id
			'Image or HTML', // title
			array( $this, 'image_or_html_2_callback' ), // callback
			'live-screenshots-admin', // page
			'live_screenshots_setting_section' // section
		);
	}

	public function live_screenshots_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['web_page_url_0'] ) ) {
			$sanitary_values['web_page_url_0'] = sanitize_text_field( $input['web_page_url_0'] );
		}

		if ( isset( $input['css_path_selector_to_capture_1'] ) ) {
			$sanitary_values['css_path_selector_to_capture_1'] = sanitize_text_field( $input['css_path_selector_to_capture_1'] );
		}

		if ( isset( $input['image_or_html_2'] ) ) {
			$sanitary_values['image_or_html_2'] = $input['image_or_html_2'];
		}

		return $sanitary_values;
	}

	public function live_screenshots_section_info() {
		
	}

	public function web_page_url_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_screenshots_option_name[web_page_url_0]" id="web_page_url_0" value="%s">',
			isset( $this->live_screenshots_options['web_page_url_0'] ) ? esc_attr( $this->live_screenshots_options['web_page_url_0']) : ''
		);
	}

	public function css_path_selector_to_capture_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_screenshots_option_name[css_path_selector_to_capture_1]" id="css_path_selector_to_capture_1" value="%s">',
			isset( $this->live_screenshots_options['css_path_selector_to_capture_1'] ) ? esc_attr( $this->live_screenshots_options['css_path_selector_to_capture_1']) : ''
		);
	}

	public function image_or_html_2_callback() {
		printf(
			'<input type="checkbox" name="live_screenshots_option_name[image_or_html_2]" id="image_or_html_2" value="image_or_html_2" %s> <label for="image_or_html_2">Do you want the result to be an image or HTML</label>',
			( isset( $this->live_screenshots_options['image_or_html_2'] ) && $this->live_screenshots_options['image_or_html_2'] === 'image_or_html_2' ) ? 'checked' : ''
		);
	}

}
if ( is_admin() )
	$live_screenshots = new LiveScreenshots();

/* 
 * Retrieve this value with:
 * $live_screenshots_options = get_option( 'live_screenshots_option_name' ); // Array of All Options
 * $web_page_url_0 = $live_screenshots_options['web_page_url_0']; // Web-page URL
 * $css_path_selector_to_capture_1 = $live_screenshots_options['css_path_selector_to_capture_1']; // CSS Path / Selector to capture
 * $image_or_html_2 = $live_screenshots_options['image_or_html_2']; // Image or HTML
 */
